# Generated by Django 6.0.6 on 2026-09-17 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0008_daymark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancesession',
            name='source',
            field=models.CharField(choices=[('SELF', 'Recorded by the staff member'), ('OWNER', 'Recorded by the boutique owner'), ('WORK', 'Recorded from the start of work')], db_index=True, default='SELF', max_length=10),
        ),
    ]
