# Generated by Django 6.0.6 on 2026-09-23 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0009_attendancesession_source_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesession',
            name='auto_checked_out',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
