# Generated by Django 6.0.6 on 2026-09-28 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm_api", "0061_merge_20260921_1828"),
        ("design_studio", "0022_customerdesign_library_asset"),
        ("staff", "0010_attendancesession_auto_checked_out"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffprofile",
            name="designer",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="staff_profile",
                to="design_studio.designer",
            ),
        ),
        migrations.AlterField(
            model_name="staffprofile",
            name="staff",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="staff_profile",
                to="crm_api.tailor",
            ),
        ),
        migrations.AddConstraint(
            model_name="staffprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("designer__isnull", True), ("staff__isnull", False)),
                    models.Q(("designer__isnull", False), ("staff__isnull", True)),
                    _connector="OR",
                ),
                name="staff_profile_belongs_to_exactly_one",
            ),
        ),
    ]
