# Generated by Django 6.0.6 on 2026-10-06 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0011_profile_designer'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesession',
            name='check_in_accuracy_m',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='check_in_distance_m',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='check_in_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='check_in_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='check_in_outside_shop',
            field=models.BooleanField(blank=True, db_index=True, null=True),
        ),
    ]
