# Generated by Django 6.0.6 on 2026-09-17 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_api', '0044_task_shaped_stage_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderstage',
            name='attachment_reviews',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
