# Generated by Django 6.0.6 on 2026-09-17 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_api', '0045_orderstage_attachment_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='flow',
            field=models.CharField(choices=[('stitching', 'Stitching'), ('maggam', 'Maggam'), ('legacy', 'Legacy')], db_index=True, default='stitching', max_length=20),
        ),
    ]
