# Generated by Django 6.0.6 on 2026-09-17 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_api', '0045_orderstage_attachment_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='instructions_voice_note',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='orderstage',
            name='voice_note',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
