# Generated by Django 6.0.6 on 2026-09-17 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_api', '0046_voice_notes'),
        ('crm_api', '0047_split_workflow_flows'),
    ]

    operations = [
    ]
