# Generated by Django 6.0.6 on 2026-09-18 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_api', '0048_merge_0046_voice_notes_0047_split_workflow_flows'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderstage',
            name='verification_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderstage',
            name='verification_seen_by',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
