# Generated by Django 6.0.6 on 2026-09-18 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_api', '0048_merge_voice_notes_and_flows'),
        ('crm_api', '0049_orderstage_verification_seen'),
    ]

    operations = [
    ]
