# Generated by Django 6.0.6 on 2026-09-18 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_api', '0050_merge_20260918_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='instructions_voice_note_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='instructions_voice_note_by',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='orderstage',
            name='voice_note_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderstage',
            name='voice_note_by',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
