# Generated by Django 6.0.6 on 2026-09-19 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_api', '0051_maggam_karigar'),
        ('crm_api', '0051_voice_note_sender'),
    ]

    operations = [
    ]
