# Generated by Django 6.0.6 on 2026-09-20 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0023_resync_type_of_design_label'),
        ('crm_api', '0056_payment_stage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderstage',
            options={'ordering': ['sequence', 'garment_job__sequence', 'id']},
        ),
        migrations.AddField(
            model_name='orderstage',
            name='garment_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='catalog.garmentjob'),
        ),
    ]
