# Generated by Django 6.0.6 on 2026-09-21 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0035_resync_ui_pass'),
        ('crm_api', '0058_split_stages_per_garment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='alteration_garment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.garmentjob'),
        ),
        migrations.AddField(
            model_name='order',
            name='alteration_garment_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='alteration_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alterations', to='crm_api.order'),
        ),
        migrations.AddField(
            model_name='order',
            name='alteration_seq',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='flow',
            field=models.CharField(choices=[('stitching', 'Stitching'), ('maggam', 'Maggam'), ('alteration', 'Alteration'), ('legacy', 'Legacy')], db_index=True, default='stitching', max_length=20),
        ),
    ]
