# Generated by Django 6.0.6 on 2026-09-21 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_api', '0059_order_media_purged_at'),
        ('crm_api', '0060_alterations_as_orders'),
    ]

    operations = [
    ]
