# Generated by Django 6.0.6 on 2026-09-28 12:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm_api", "0061_merge_20260921_1828"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerReferral",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "referrer_name_snapshot",
                    models.CharField(blank=True, default="", max_length=201),
                ),
                (
                    "referrer_mobile_snapshot",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("note", models.TextField(blank=True, default="")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "referred",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referrals_received",
                        to="crm_api.customer",
                    ),
                ),
                (
                    "referrer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="referrals_made",
                        to="crm_api.customer",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("referrer", models.F("referred")), _negated=True
                        ),
                        name="customer_referral_not_self",
                    ),
                    models.UniqueConstraint(
                        fields=("referred",), name="customer_referral_one_referrer"
                    ),
                    models.UniqueConstraint(
                        fields=("referrer", "referred"),
                        name="customer_referral_unique_pair",
                    ),
                ],
            },
        ),
    ]
