# Generated by Django 6.0.6 on 2026-09-30 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_api', '0062_customerreferral'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='internal_number',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='order',
            name='kind',
            field=models.CharField(choices=[('customer', 'Customer order'), ('internal', 'Boutique stock')], db_index=True, default='customer', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='crm_api.customer'),
        ),
    ]
