# Generated by Django 6.0.6 on 2026-10-06 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_api', '0063_order_internal_number_order_kind_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boutiquesettings',
            name='shop_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='boutiquesettings',
            name='shop_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='boutiquesettings',
            name='shop_radius_m',
            field=models.PositiveIntegerField(default=150),
        ),
    ]
