# Generated by Django 6.0.6 on 2026-10-07 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_api', '0066_merge_shop_location_maggam_karigar'),
    ]

    operations = [
        migrations.AddField(
            model_name='designpreference',
            name='reference_parts',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
