# Generated by Django 6.0.6 on 2026-09-20 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0023_resync_type_of_design_label'),
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productiontask',
            name='garment_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='production_tasks', to='catalog.garmentjob'),
        ),
    ]
