# Generated by Django 6.0.6 on 2026-09-23 10:58

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_api', '0061_merge_20260921_1828'),
        ('finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('received_on', models.DateField(db_index=True)),
                ('method', models.CharField(choices=[('CASH', 'Cash'), ('UPI', 'UPI'), ('CARD', 'Card'), ('BANK', 'Bank transfer'), ('OTHER', 'Other')], default='CASH', max_length=10)),
                ('source', models.CharField(choices=[('RECORDED', 'Recorded at the counter'), ('SNAPSHOT', 'Derived from the order total'), ('BACKFILL', 'Recorded before payments were dated')], db_index=True, default='RECORDED', max_length=10)),
                ('reference', models.CharField(blank=True, default='', max_length=100)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_recorded', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='crm_api.order')),
            ],
            options={
                'ordering': ['-received_on', '-created_at'],
                'indexes': [models.Index(fields=['received_on', 'order'], name='finance_pay_receive_5bb17e_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='finance_payment_amount_not_negative')],
            },
        ),
    ]
