# Generated by Django 6.0.6 on 2026-09-15 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_whatsappaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='boutiquetenant',
            name='color_mode',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('system', 'Match device')], default='light', max_length=16),
        ),
        migrations.AddField(
            model_name='boutiquetenant',
            name='design_system',
            field=models.CharField(choices=[('scaleezy', 'Scaleezy'), ('atelier', 'Atelier')], default='scaleezy', max_length=32),
        ),
    ]
