# Generated by Django 6.0.6 on 2026-09-17 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0007_boutiquetenant_appearance'),
    ]

    operations = [
        migrations.AddField(
            model_name='boutiquetenant',
            name='plan',
            # Before plans existed every boutique had the whole product; the
            # default keeps it that way for them.
            field=models.CharField(default='atelier', max_length=20),
        ),
        migrations.AlterField(
            model_name='boutiquetenant',
            name='enabled_modules',
            field=models.JSONField(blank=True, default=dict, help_text='Overrides on top of the plan, as {module_key: true/false}: an add-on bought, or a module granted or withheld by hand. A module not listed follows the plan.'),
        ),
    ]
