# Generated by Django 6.0.6 on 2026-09-24 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0008_boutiquetenant_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='boutiquetenant',
            name='owner_password_temporary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='demorequest',
            name='address',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='demorequest',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demorequest',
            name='approved_by',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='demorequest',
            name='source',
            field=models.CharField(choices=[('website', 'Website demo form'), ('app', 'App access request')], default='website', max_length=20),
        ),
        migrations.AddField(
            model_name='demorequest',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_requests', to='tenants.boutiquetenant'),
        ),
        migrations.AddField(
            model_name='demorequest',
            name='welcome_emailed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
