# Generated by Django 6.0.6 on 2026-10-05 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0009_boutiquetenant_shop_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, default='', help_text='Which portal this is, for the person revoking it later.', max_length=100)),
                ('key_id', models.CharField(db_index=True, max_length=32, unique=True)),
                ('secret_hash', models.CharField(max_length=64)),
                ('allowed_origin', models.CharField(blank=True, default='', help_text='e.g. https://sarala.example.com. Blank sends no CORS header, so only same-origin and non-browser callers can read a reply.', max_length=200)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_credentials', to='tenants.boutiquetenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
