# Generated by Django 6.0.6 on 2026-10-01 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
