# Generated by Django 6.0.6 on 2026-10-06 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_api', '0065_maggam_karigar_on_maggam_work'),
        ('todos', '0002_todo_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='order_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='todos', to='crm_api.orderstage'),
        ),
    ]
