# Generated by Django 6.0.6 on 2026-09-15 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alterations', '0002_add_missing_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='alterationrequest',
            name='issue_scale',
            field=models.CharField(blank=True, choices=[('SMALL', 'Small'), ('BIG', 'Big')], db_index=True, default='', max_length=10),
        ),
    ]
