# Generated by Django 6.0.6 on 2026-09-15 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alterations', '0003_alterationrequest_issue_scale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alterationrequest',
            name='status',
            field=models.CharField(choices=[('RECEIVED', 'Received'), ('INSPECTION', 'Inspection'), ('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('QC', 'Quality Check'), ('CUSTOMER_REVIEW', 'Customer Review'), ('PRESSING', 'Pressing'), ('PACKAGING', 'Packaging'), ('READY_FOR_PICKUP', 'Ready for Pickup'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='RECEIVED', max_length=50),
        ),
    ]
