# Generated by Django 6.0.6 on 2026-09-15 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alterations', '0004_small_issue_statuses'),
        ('catalog', '0012_backfill_garmentjob_selections'),
        ('crm_api', '0043_retire_fabric_catalogue'),
    ]

    operations = [
        migrations.AddField(
            model_name='alterationrequest',
            name='garment_note',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='alterationrequest',
            name='garment_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outside_alterations', to='catalog.garmenttemplate'),
        ),
        migrations.AddField(
            model_name='alterationrequest',
            name='intake_photo_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='alterationrequest',
            name='origin',
            field=models.CharField(choices=[('OWN', 'Our own order'), ('OUTSIDE', 'Brought from outside')], db_index=True, default='OWN', max_length=10),
        ),
        migrations.AlterField(
            model_name='alterationrequest',
            name='garment_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='alteration_requests', to='catalog.garmentjob'),
        ),
        migrations.AlterField(
            model_name='alterationrequest',
            name='original_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='alteration_requests', to='crm_api.order'),
        ),
    ]
