# Generated by Django 6.0.6 on 2026-09-16 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0006_auditlog_appearance_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('login', 'Boutique sign-in'), ('console', 'Console sign-in'), ('reset', 'Password reset requested')], db_index=True, max_length=10)),
                ('username', models.CharField(blank=True, db_index=True, max_length=150)),
                ('boutique', models.CharField(blank=True, db_index=True, max_length=63)),
                ('ip', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('ok', models.BooleanField()),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-at'],
                'indexes': [models.Index(fields=['ok', '-at'], name='superadmin__ok_16c1da_idx')],
            },
        ),
    ]
