# Generated by Django 6.0.6 on 2026-09-15 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design_studio', '0020_customerdesign'),
        ('inventory', '0012_fabric_catalogue_into_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='design_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stocked_as', to='design_studio.designasset'),
        ),
        migrations.AlterField(
            model_name='catalogitem',
            name='legacy_category',
            field=models.CharField(choices=[('FABRIC', 'Fabric'), ('BORDER', 'Border & Trim'), ('LINING', 'Lining'), ('EMBELLISHMENT', 'Embellishment'), ('STITCHING', 'Stitching Material'), ('PACKAGING', 'Packaging'), ('MAGGAM', 'Maggam / Embroidery'), ('DESIGN', 'Design'), ('OTHER', 'Other')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='category',
            field=models.CharField(choices=[('FABRIC', 'Fabric'), ('BORDER', 'Border & Trim'), ('LINING', 'Lining'), ('EMBELLISHMENT', 'Embellishment'), ('STITCHING', 'Stitching Material'), ('PACKAGING', 'Packaging'), ('MAGGAM', 'Maggam / Embroidery'), ('DESIGN', 'Design'), ('OTHER', 'Other')], db_index=True, max_length=30),
        ),
    ]
