# Generated by Django 6.0.6 on 2026-09-20 17:37

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0028_order_purchase'),
        ('crm_api', '0058_split_stages_per_garment'),
        ('inventory', '0014_only_main_store'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderPurchase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_key', models.CharField(blank=True, default='', max_length=60)),
                ('garment_name', models.CharField(blank=True, default='', max_length=150)),
                ('name', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True, default='')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('unit', models.CharField(choices=[('METER', 'Meter'), ('PIECE', 'Piece'), ('PAIR', 'Pair'), ('ROLL', 'Roll'), ('PACKET', 'Packet'), ('BOX', 'Box'), ('SET', 'Set'), ('KILOGRAM', 'Kilogram'), ('GRAM', 'Gram'), ('STRING', 'String'), ('UNIT', 'Unit')], default='PIECE', max_length=20)),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('actual_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('invoice_reference', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('TO_PURCHASE', 'To purchase'), ('PURCHASED', 'Purchased'), ('RECEIVED', 'Received'), ('USED', 'Used'), ('CANCELLED', 'Cancelled')], db_index=True, default='TO_PURCHASE', max_length=20)),
                ('required_by', models.DateField(blank=True, null=True)),
                ('purchased_at', models.DateField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('received_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('used_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('garment_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='catalog.garmentjob')),
                ('job_material', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase', to='catalog.jobmaterial')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='crm_api.order')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_purchases', to='inventory.supplier')),
            ],
            options={
                'ordering': ['required_by', 'created_at'],
            },
        ),
    ]
