# Generated by Django 6.0.6 on 2026-09-30 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_order_purchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogitem',
            name='legacy_category',
            field=models.CharField(choices=[('FABRIC', 'Fabric'), ('BORDER', 'Border & Trim'), ('LINING', 'Lining'), ('EMBELLISHMENT', 'Embellishment'), ('STITCHING', 'Stitching Material'), ('PACKAGING', 'Packaging'), ('MAGGAM', 'Maggam / Embroidery'), ('DESIGN', 'Design'), ('FINISHED', 'Finished garment'), ('OTHER', 'Other')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='category',
            field=models.CharField(choices=[('FABRIC', 'Fabric'), ('BORDER', 'Border & Trim'), ('LINING', 'Lining'), ('EMBELLISHMENT', 'Embellishment'), ('STITCHING', 'Stitching Material'), ('PACKAGING', 'Packaging'), ('MAGGAM', 'Maggam / Embroidery'), ('DESIGN', 'Design'), ('FINISHED', 'Finished garment'), ('OTHER', 'Other')], db_index=True, max_length=30),
        ),
    ]
