# Generated by Django 6.0.6 on 2026-09-23 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='custom_type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_type',
            field=models.CharField(choices=[('CONSULTATION', 'Design Consultation'), ('MEASUREMENT', 'Measurement Fitting'), ('TRIAL', 'Garment Trial'), ('DELIVERY', 'Final Delivery'), ('OTHER', 'Other')], db_index=True, default='TRIAL', max_length=50),
        ),
    ]
