# Generated by Django 6.0.6 on 2026-09-17 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design_studio', '0021_designasset_image_url_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdesign',
            name='library_asset',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_design', to='design_studio.designasset'),
        ),
    ]
