# Generated by Django 6.0.6 on 2026-09-15 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_backfill_garmentjob_selections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatefield',
            name='inventory_category',
            field=models.CharField(blank=True, choices=[('FABRIC', 'Fabric'), ('BORDER', 'Border & Trim'), ('LINING', 'Lining'), ('EMBELLISHMENT', 'Embellishment'), ('STITCHING', 'Stitching Material'), ('PACKAGING', 'Packaging'), ('MAGGAM', 'Maggam / Embroidery'), ('DESIGN', 'Design'), ('OTHER', 'Other')], max_length=30, null=True),
        ),
    ]
