# Generated by Django 6.0.6 on 2026-09-20 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0027_resync_sharara_measurements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobmaterial',
            name='source',
            field=models.CharField(choices=[('STORE', 'Store inventory'), ('CUSTOMER', 'Customer provided'), ('PURCHASE', 'Bought for this order')], default='STORE', max_length=20),
        ),
    ]
