# Generated by Django 6.0.6 on 2026-09-20 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0028_order_purchase'),
        ('catalog', '0032_resync_pattern_details'),
    ]

    operations = [
    ]
